name: data_privacy_analytics
version: 1.0.0
config-version: 2

profile: data_privacy_analytics

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  data_privacy_analytics:
    drop_clean_ca:
      +tags: [drop_clean_ca]
      +materialized: table
