substitutions:
  _REGION: us-east4
  _PROJECT: example-gcp-project
  _SERVICE: drop-ingestor-dev
  _TAG: latest
  _CLOUDSQL_INSTANCE: example-gcp-project:us-east4:dpra-dev-temp

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/${_PROJECT}/data-privacy/${_SERVICE}:${_TAG}
      - -f
      - app/drop_ingestor/Dockerfile
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-east4-docker.pkg.dev/${_PROJECT}/data-privacy/${_SERVICE}:${_TAG}

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=us-east4-docker.pkg.dev/${_PROJECT}/data-privacy/${_SERVICE}:${_TAG}
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
      - --add-cloudsql-instances=${_CLOUDSQL_INSTANCE}
      - --set-env-vars=SERVICE_NAME=drop-ingestor,WORKER_ID=drop-ingestor-dev,GCP_PROJECT=${_PROJECT},LOG_LEVEL=INFO,DATABASE_URL=${_DATABASE_URL}

images:
  - us-east4-docker.pkg.dev/${_PROJECT}/data-privacy/${_SERVICE}:${_TAG}
